env:
  node: true
  commonjs: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
rules:
  no-console: 0
  import/extensions: 0

overrides:
  - files:
      - "**/*.test.js"
    env:
      jest: true
